server:
  port: 9095

spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@microlearndb.9tj1xza.mongodb.net/?retryWrites=true&w=majority&appName=MicroLearnDB
      database: MicroLearnDB
  application:
    name: transaction-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: microlearnc@gmail.com
    password: laic stji jscg khtj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    hostname: transaction-service

